In [36]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler    
from sklearn.linear_model import LogisticRegression  
from sklearn.metrics import confusion_matrix  ,accuracy_score,classification_report
import matplotlib.pyplot as mtp 


In [2]:
data=load_iris()

In [3]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df=pd.DataFrame(data.data,columns=data.feature_names)


In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:

data.keys()



dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
x,y=datasets.load_iris(return_X_y=True)

In [10]:
df['target'].unique()

KeyError: 'target'

In [11]:
df['target']=y

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
df['target'].unique()

array([0, 1, 2])

In [17]:
df_copy=df[df['target']!=2]

In [18]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [19]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [20]:
df_copy['target'].unique()

array([0, 1])

In [21]:
x=df_copy.iloc[:,:-1].values
y=df_copy.iloc[:,-1].values

In [25]:
#training the data
x_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.40, random_state=42)

In [26]:
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

GaussianNB()

In [27]:
len(X_train),len(y_train),len(X_test),len(y_test)

(60, 60, 40, 40)

In [28]:
st_x= StandardScaler()    
x_train= st_x.fit_transform(X_train)    
x_test= st_x.transform(X_test)  
x_train

array([[-0.74456544,  0.59434687, -1.11803733, -1.1296877 ],
       [-0.89249234,  0.15135541, -1.04644476, -1.1296877 ],
       [-0.74456544,  0.8158426 , -1.04644476, -1.1296877 ],
       [ 0.29092292, -0.07014031,  0.88655468,  0.68264551],
       [-0.44871162,  1.03733833, -1.04644476, -1.1296877 ],
       [-0.59663853,  1.70182552, -1.04644476, -0.94845438],
       [-0.0049309 , -1.39911469,  0.52859182,  0.32017887],
       [-0.74456544, -0.07014031, -0.97485219, -1.1296877 ],
       [ 0.73470364, -1.84210614,  0.74336954,  0.32017887],
       [-1.78005379, -0.07014031, -1.33281505, -1.31092102],
       [-1.04041925,  0.8158426 , -0.76007447, -1.1296877 ],
       [-1.33627307,  0.15135541, -1.04644476, -1.1296877 ],
       [-0.59663853,  1.03733833, -1.11803733, -0.94845438],
       [-1.63212688, -0.07014031, -1.1896299 , -1.1296877 ],
       [-1.63212688, -0.29163604, -1.11803733, -1.1296877 ],
       [ 0.73470364, -0.29163604,  1.1013324 ,  1.22634547],
       [-1.33627307,  0.

In [29]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [30]:
y_pred = classifier.predict(x_test)  

In [38]:

cm = confusion_matrix(y_test, y_pred)  


In [39]:
#accuracy
print(accuracy_score(y_pred,y_test))

0.425


In [41]:
#classification_Report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.42      0.60        40

    accuracy                           0.42        40
   macro avg       0.50      0.21      0.30        40
weighted avg       1.00      0.42      0.60        40



C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
